include classpath("application.conf")

node-address {
  protocol = http
  host = "0.0.0.0"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = relaxed
}

queues {
  keystone-events {
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    visibilityTimeout = 30 seconds
  }
}